[tool.poetry]
name = "datura-ai"
version = "0.1.0"
description = ""
authors = ["Sergej Műller <millerserhii@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
