"""add sentiment analysis model

Revision ID: 03ae6a62418a
Revises: 5777a6752bed
Create Date: 2025-03-22 18:29:43.205540

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "03ae6a62418a"
down_revision: Union[str, None] = "5777a6752bed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sentiment_analyses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("netuid", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("tweets_count", sa.Integer(), nullable=False),
        sa.Column(
            "operation_type",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("stake_amount", sa.Float(), nullable=False),
        sa.Column(
            "tweets_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sentiment_analyses_id"),
        "sentiment_analyses",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sentiment_analyses_netuid"),
        "sentiment_analyses",
        ["netuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sentiment_analyses_netuid"), table_name="sentiment_analyses"
    )
    op.drop_index(
        op.f("ix_sentiment_analyses_id"), table_name="sentiment_analyses"
    )
    op.drop_table("sentiment_analyses")
    # ### end Alembic commands ###
