"""Create initial tables

Revision ID: 5777a6752bed
Revises:
Create Date: 2025-03-22 13:40:42.662483

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5777a6752bed"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dividend_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("netuid", sa.Integer(), nullable=False),
        sa.Column(
            "hotkey", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("dividend_value", sa.Integer(), nullable=False),
        sa.Column(
            "source", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dividend_history_hotkey"),
        "dividend_history",
        ["hotkey"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dividend_history_id"),
        "dividend_history",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dividend_history_netuid"),
        "dividend_history",
        ["netuid"],
        unique=False,
    )
    op.create_table(
        "stake_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "operation_type",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("netuid", sa.Integer(), nullable=False),
        sa.Column(
            "hotkey", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "tx_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sentiment_score", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stake_transactions_hotkey"),
        "stake_transactions",
        ["hotkey"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stake_transactions_id"),
        "stake_transactions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stake_transactions_netuid"),
        "stake_transactions",
        ["netuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stake_transactions_operation_type"),
        "stake_transactions",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stake_transactions_tx_hash"),
        "stake_transactions",
        ["tx_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stake_transactions_tx_hash"), table_name="stake_transactions"
    )
    op.drop_index(
        op.f("ix_stake_transactions_operation_type"),
        table_name="stake_transactions",
    )
    op.drop_index(
        op.f("ix_stake_transactions_netuid"), table_name="stake_transactions"
    )
    op.drop_index(
        op.f("ix_stake_transactions_id"), table_name="stake_transactions"
    )
    op.drop_index(
        op.f("ix_stake_transactions_hotkey"), table_name="stake_transactions"
    )
    op.drop_table("stake_transactions")
    op.drop_index(
        op.f("ix_dividend_history_netuid"), table_name="dividend_history"
    )
    op.drop_index(
        op.f("ix_dividend_history_id"), table_name="dividend_history"
    )
    op.drop_index(
        op.f("ix_dividend_history_hotkey"), table_name="dividend_history"
    )
    op.drop_table("dividend_history")
    # ### end Alembic commands ###
